### ISSUE TITLE
On Scroll product isn't loading

### ISSUE THREAD

**Issue by y4ahmad** [Strategery-Inc/Magento2-InfiniteScroll#26]
I am using a this free module. When I scroll down ajax request initiate and response come with new page content . But this response not updating on current content. Can anyone suggest the solution for this

**Comment by gsomoza** [comment]
You may have some compatibility issue(s) with 3rd-party extensions or custom code. Could you try disabling other extensions to see if at least the Infinite Scroll functionality works?

**Comment by y4ahmad** [comment]
Hello @gsomoza ,

Thanks for your suggestion. I tried with that and yes it worked for me.  But due to this I am unable to use the other extension. In that case can you please suggest me any ajax filter which is compatible with Infinite Scroll?

**Comment by gsomoza** [comment]
Any AJAX-related extensions that heavily modify the way the catalog pages are displayed/rendered will have conflicts with our extension. This means that a developer will have to integrate them together manually. 

Unfortunately this is not something we can do ourselves because this is a free extension and there are dozens of other extensions that we would have to provide (and maintain!) compatibility for. Most of the code in this extension was built by several people during their free time, as a way to give back to the Magento community.

If you have the resources, I recommend you ask your developer to make the integration. And if that works out it would be awesome if you could then submit the integration code to this repository so that other people can benefit as well!
