### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by zap263** [Strategery-Inc/Magento2-InfiniteScroll#55]
Hi.. I would just like to know before I install this if it supports pagination too?  And will clicking the back button remember the position in the catalog or revert back to top?

**Comment by gsomoza** [comment]
This actually uses pagination features to fetch the next pages, while optionally hiding the toolbar as well (can be configured).

Navigating "back" is one of the most complicated aspects of infinite scroll pagination in general, not only technical but also from an UX perspective. In order to stay "simple", this plugin is very dumb in that sense: it will simply take you back to the page where you were and show you whatever number of products you can see in a single page. It's like going back to a single page.
